# This is a basic workflow to help you get started with Actions

name: CI-local

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the reorganize branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Log in to docker hub. 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:  
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 


      # Runs a single command using the runners shell
      - name: Installation
        run: |
          cd $GITHUB_WORKSPACE
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          hash -r
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda config --append envs_dirs $HOME/miniconda/envs 
          conda create -n neurocaas
          conda activate neurocaas
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aws-sam-cli==0.53.0 
          pip install localstack==0.12.3
          pip install ./ 
          sudo apt-get install jq

      - name: Pull hello-world image
        run: docker pull hello-world
         
      - name: Start localstack    
        run: localstack start --host 

      - name: Run tests
        run: |
          echo $HOME $GITHUB_WORKSPACE "locations."
          ls $HOME/miniconda/bin
          ls $HOME/miniconda/envs
          conda config --describe envs_dirs
          conda env list
          
          pytest tests/protocol_tests/test_submit_start.py
        env:
          AWS_DEFAULT_REGION: "us-east-1"

